/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stack;

import javax.swing.table.DefaultTableModel;
import java.util.Stack;

/**
 *
 * @author ponlawatchangto
 */
public class MainGUI extends javax.swing.JFrame {

    Info stack;
    int stackSize;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        this.setLocationRelativeTo(null);

        SizeInputDialog inputSizeDialog = new SizeInputDialog(this, true);;
        inputSizeDialog.setVisible(true);

        stackSize = inputSizeDialog.getInputSize();
        stack = new Info(stackSize);
        DefaultTableModel model = (DefaultTableModel) tableStackA.getModel();
        model.setRowCount(stackSize);
        model = (DefaultTableModel) tableStackB.getModel();
        model.setRowCount(stackSize);
        model = (DefaultTableModel) tableStackC.getModel();
        model.setRowCount(stackSize);

        InputStackGUI inputStackDialog = new InputStackGUI(this, true);
        inputStackDialog.setVisible(true);

        if (inputStackDialog.getTestPass()) {
            for (int i = 0; i < stackSize; i++) {
                tableStackA.setValueAt(stack.getStackA().push(inputStackDialog.getValueFromTable(i)), i, 0);
            }
            showStack(stack.getStackA());
        } else if (stackSize > 10) {
            for (int i = 0; i < stackSize; i++) {
                tableStackA.setValueAt(stack.getStackA().push(inputStackDialog.getValueFromTable(i)), i, 0);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stackAPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStackA = new javax.swing.JTable();
        stackBPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableStackB = new javax.swing.JTable();
        stackCPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableStackC = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        moveAToB_Button = new javax.swing.JButton();
        moveBToA_Button = new javax.swing.JButton();
        moveBToC_Button = new javax.swing.JButton();
        moveCToB_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stackAPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tableStackA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"10"},
                {"9"},
                {"8"},
                {"7"},
                {"6"},
                {"5"},
                {"4"},
                {"3"},
                {"2"},
                {"1"}
            },
            new String [] {
                "Stack A"
            }
        ));
        jScrollPane1.setViewportView(tableStackA);

        javax.swing.GroupLayout stackAPanelLayout = new javax.swing.GroupLayout(stackAPanel);
        stackAPanel.setLayout(stackAPanelLayout);
        stackAPanelLayout.setHorizontalGroup(
            stackAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stackAPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        stackAPanelLayout.setVerticalGroup(
            stackAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stackAPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        stackBPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tableStackB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Stack B"
            }
        ));
        jScrollPane2.setViewportView(tableStackB);

        javax.swing.GroupLayout stackBPanelLayout = new javax.swing.GroupLayout(stackBPanel);
        stackBPanel.setLayout(stackBPanelLayout);
        stackBPanelLayout.setHorizontalGroup(
            stackBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stackBPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        stackBPanelLayout.setVerticalGroup(
            stackBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stackBPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stackCPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tableStackC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Stack C"
            }
        ));
        jScrollPane3.setViewportView(tableStackC);

        javax.swing.GroupLayout stackCPanelLayout = new javax.swing.GroupLayout(stackCPanel);
        stackCPanel.setLayout(stackCPanelLayout);
        stackCPanelLayout.setHorizontalGroup(
            stackCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stackCPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        stackCPanelLayout.setVerticalGroup(
            stackCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stackCPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        moveAToB_Button.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        moveAToB_Button.setText("Move A to B");
        moveAToB_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveAToB_ButtonActionPerformed(evt);
            }
        });

        moveBToA_Button.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        moveBToA_Button.setText("Move B to A");
        moveBToA_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBToA_ButtonActionPerformed(evt);
            }
        });

        moveBToC_Button.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        moveBToC_Button.setText("Move B to C");
        moveBToC_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBToC_ButtonActionPerformed(evt);
            }
        });

        moveCToB_Button.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        moveCToB_Button.setText("Move C to B");
        moveCToB_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveCToB_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(moveAToB_Button)
                .addGap(34, 34, 34)
                .addComponent(moveBToA_Button)
                .addGap(18, 18, 18)
                .addComponent(moveBToC_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(moveCToB_Button)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveAToB_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moveBToA_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moveBToC_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moveCToB_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel1.setText("Stack Assignment 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(stackAPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(stackBPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(stackCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(stackCPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stackBPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stackAPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moveAToB_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveAToB_ButtonActionPerformed
        // TODO add your handling code here:
        if (stack.getStackA().isEmpty()) {
            return ;
        }
        
        try {
            for (int i = 0; i < stackSize; i++) {
                System.out.println("Move A to B at i = " + i);
                tableStackB.setValueAt(stack.getStackB().push((stack.getStackA().pop())), i, 0);
                tableStackA.setValueAt(null, i, 0);
            }
            if (!stack.getStackA().isEmpty()) {
                System.out.println("Printing StackA in move A to B");
                showStack(stack.getStackA());
            }
            if (!stack.getStackB().isEmpty()) {
                System.out.println("Printing StackB in move A to B");
                showStack(stack.getStackB());
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error occured");
        }

    }//GEN-LAST:event_moveAToB_ButtonActionPerformed

    private void moveBToA_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveBToA_ButtonActionPerformed
        // TODO add your handling code here:
        if (stack.getStackB().isEmpty()){
            return ;
        }
        
        try {
            for (int i = 0; i < stackSize; i++) {
                System.out.println("Move B to A at i = " + i);
                tableStackA.setValueAt(stack.getStackA().push((stack.getStackB().pop())), i, 0);
                tableStackB.setValueAt(null, i, 0);
            }
            if (!stack.getStackB().isEmpty()) {
                System.out.println("Printing StackB in move B to A");
                showStack(stack.getStackB());
            }
            if (!stack.getStackA().isEmpty()) {
                System.out.println("Printing StackA in move B to A");
                showStack(stack.getStackA());
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error occured");
        }
    }//GEN-LAST:event_moveBToA_ButtonActionPerformed

    private void moveBToC_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveBToC_ButtonActionPerformed
        // TODO add your handling code here:
        if (stack.getStackB().isEmpty()) {
            return ;
        }
        
        try {
            for (int i = 0 ; i < stackSize ; i++ ) {
                System.out.println("Move B to C at i = " + i);
                tableStackC.setValueAt(stack.getStackC().push(stack.getStackB().pop()), i, 0);
                tableStackB.setValueAt(null, i, 0);
            }
            if (!stack.getStackB().isEmpty()) {
                System.out.println("Printing StackB in move B to C");
                showStack(stack.getStackB()) ;
            }
            if (!stack.getStackC().isEmpty()) {
                System.out.println("Printing StackC in move B to A");
                showStack(stack.getStackC());
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_moveBToC_ButtonActionPerformed

    private void moveCToB_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveCToB_ButtonActionPerformed
        // TODO add your handling code here:
        if (stack.getStackC().isEmpty()) {
            return ;
        }
        
        try {
            for (int i = 0; i < stackSize; i++) {
                System.out.println("Move A to B at i = " + i);
                tableStackB.setValueAt(stack.getStackB().push((stack.getStackC().pop())), i, 0);
                tableStackC.setValueAt(null, i, 0);
            }
            if (!stack.getStackC().isEmpty()) {
                System.out.println("Printing StackC in move C to B");
                showStack(stack.getStackC());
            }
            if (!stack.getStackB().isEmpty()) {
                System.out.println("Printing StackB in move C to B");
                showStack(stack.getStackB());
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error occured");
        }
    }//GEN-LAST:event_moveCToB_ButtonActionPerformed


    int getStackSize() {
        return stackSize;
    }

    void showStack(Stack<Integer> item) {
        System.out.print("{");
        for (int i = 0; i < stackSize; i++) {
            System.out.print(item.get(i));
            if (i != stackSize - 1) {
                System.out.print(",");
            }
        }
        System.out.println("}");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton moveAToB_Button;
    private javax.swing.JButton moveBToA_Button;
    private javax.swing.JButton moveBToC_Button;
    private javax.swing.JButton moveCToB_Button;
    private javax.swing.JPanel stackAPanel;
    private javax.swing.JPanel stackBPanel;
    private javax.swing.JPanel stackCPanel;
    private javax.swing.JTable tableStackA;
    private javax.swing.JTable tableStackB;
    private javax.swing.JTable tableStackC;
    // End of variables declaration//GEN-END:variables
}
