/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2103_assignment2.pkg1;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ponlawatchangto
 */
public class MainGUI extends javax.swing.JFrame {
    Stack stackA ;
    Stack stackB ;
    Stack stackC ;
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }
    public MainGUI(Stack stack) {
        initComponents();
        this.setLocationRelativeTo(null);
        stackA = new Stack(stack) ;
        stackB = new Stack(stackA.maxsize) ;
        stackC = new Stack(stackA.maxsize) ;
        updateStackA() ;
        updateStackB() ;
        updateStackC() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StackATable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        AtoB = new javax.swing.JButton();
        AtoC = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StackBTable = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        BtoA = new javax.swing.JButton();
        BtoC = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        StackCTable = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        CtoB = new javax.swing.JButton();
        CtoA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Anakotmai", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Assignment 2.1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(244, 244, 244))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        StackATable.setFont(new java.awt.Font("Anakotmai", 0, 18)); // NOI18N
        StackATable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stack A"
            }
        ));
        jScrollPane1.setViewportView(StackATable);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        AtoB.setBackground(new java.awt.Color(255, 166, 6));
        AtoB.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        AtoB.setForeground(new java.awt.Color(0, 0, 0));
        AtoB.setText("Move A to B");
        AtoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtoBActionPerformed(evt);
            }
        });

        AtoC.setBackground(new java.awt.Color(255, 166, 6));
        AtoC.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        AtoC.setForeground(new java.awt.Color(0, 0, 0));
        AtoC.setText("Move A to C");
        AtoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtoCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AtoC)
                    .addComponent(AtoB))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AtoB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AtoC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        StackBTable.setFont(new java.awt.Font("Anakotmai", 0, 18)); // NOI18N
        StackBTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stack B"
            }
        ));
        jScrollPane2.setViewportView(StackBTable);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        BtoA.setBackground(new java.awt.Color(255, 166, 6));
        BtoA.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        BtoA.setForeground(new java.awt.Color(0, 0, 0));
        BtoA.setText("Move B to A");
        BtoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoAActionPerformed(evt);
            }
        });

        BtoC.setBackground(new java.awt.Color(255, 166, 6));
        BtoC.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        BtoC.setForeground(new java.awt.Color(0, 0, 0));
        BtoC.setText("Move B to C");
        BtoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtoCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtoA)
                    .addComponent(BtoC))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtoA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtoC)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        StackCTable.setFont(new java.awt.Font("Anakotmai", 0, 18)); // NOI18N
        StackCTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stack C"
            }
        ));
        jScrollPane3.setViewportView(StackCTable);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        CtoB.setBackground(new java.awt.Color(255, 166, 6));
        CtoB.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        CtoB.setForeground(new java.awt.Color(0, 0, 0));
        CtoB.setText("Move C to B");
        CtoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CtoBActionPerformed(evt);
            }
        });

        CtoA.setBackground(new java.awt.Color(255, 166, 6));
        CtoA.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        CtoA.setForeground(new java.awt.Color(0, 0, 0));
        CtoA.setText("Move C to A");
        CtoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CtoAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CtoA)
                    .addComponent(CtoB))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CtoB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CtoA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CtoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CtoBActionPerformed
        if (stackC.checkEmpty() || stackB.checkFull()){
            ErrorDialog dialog = new ErrorDialog(this,true) ;
            dialog.setVisible(true);
        } else {
            try{
                System.out.println("Transfer C to B , Start") ;
                stackB.push(stackC.pop());
                System.out.println("Transfer C to B , Success");
                updateStackC() ;
                updateStackB() ;
            } catch (Exception e) {
                System.out.println("Transfer C to B , Failed");
                e.printStackTrace() ;
                ErrorDialog dialog = new ErrorDialog(this,true) ;
                dialog.setVisible(true);
            }
            
        }
    }//GEN-LAST:event_CtoBActionPerformed

    private void AtoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtoBActionPerformed
        if (stackA.checkEmpty() || stackB.checkFull()){
            ErrorDialog dialog = new ErrorDialog(this,true) ;
            dialog.setVisible(true);
        } else {
            try{
                System.out.println("Transfer A to B , Start") ;
                stackB.push(stackA.pop());
                System.out.println("Transfer A to B , Success");
                updateStackA() ;
                updateStackB() ;
            } catch (Exception e) {
                System.out.println("Transfer A to B , Failed");
                e.printStackTrace() ;
                ErrorDialog dialog = new ErrorDialog(this,true) ;
                dialog.setVisible(true);
            }
            
        }
    }//GEN-LAST:event_AtoBActionPerformed

    private void BtoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoAActionPerformed
        if (stackB.checkEmpty() || stackA.checkFull()){
            ErrorDialog dialog = new ErrorDialog(this,true) ;
            dialog.setVisible(true);
        } else {
            try{
                System.out.println("Transfer B to A , Start") ;
                stackA.push(stackB.pop());
                System.out.println("Transfer B to A , Success");
                updateStackA() ;
                updateStackB() ;
            } catch (Exception e) {
                System.out.println("Transfer B to A , Failed");
                e.printStackTrace() ;
                ErrorDialog dialog = new ErrorDialog(this,true) ;
                dialog.setVisible(true);
            }
            
        }
    }//GEN-LAST:event_BtoAActionPerformed

    private void BtoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtoCActionPerformed
        if (stackB.checkEmpty() || stackC.checkFull()){
            ErrorDialog dialog = new ErrorDialog(this,true) ;
            dialog.setVisible(true);
        } else {
            try{
                System.out.println("Transfer B to C , Start") ;
                stackC.push(stackB.pop());
                System.out.println("Transfer B to C , Success");
                updateStackB() ;
                updateStackC() ;
            } catch (Exception e) {
                System.out.println("Transfer B to C , Failed");
                e.printStackTrace() ;
                ErrorDialog dialog = new ErrorDialog(this,true) ;
                dialog.setVisible(true);
            }
            
        }
    }//GEN-LAST:event_BtoCActionPerformed

    private void AtoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtoCActionPerformed
        if (stackA.checkEmpty() || stackC.checkFull()){
            ErrorDialog dialog = new ErrorDialog(this,true) ;
            dialog.setVisible(true);
        } else {
            try{
                System.out.println("Transfer A to C , Start") ;
                stackC.push(stackA.pop());
                System.out.println("Transfer A to C , Success");
                updateStackA() ;
                updateStackC() ;
            } catch (Exception e) {
                System.out.println("Transfer A to C , Failed");
                e.printStackTrace() ;
                ErrorDialog dialog = new ErrorDialog(this,true) ;
                dialog.setVisible(true);
            }
            
        }
    }//GEN-LAST:event_AtoCActionPerformed

    private void CtoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CtoAActionPerformed
        if (stackC.checkEmpty() || stackA.checkFull()){
            ErrorDialog dialog = new ErrorDialog(this,true) ;
            dialog.setVisible(true);
        } else {
            try{
                System.out.println("Transfer C to A , Start") ;
                stackA.push(stackC.pop());
                System.out.println("Transfer C to A , Success");
                updateStackA() ;
                updateStackC() ;
            } catch (Exception e) {
                System.out.println("Transfer C to A , Failed");
                e.printStackTrace() ;
                ErrorDialog dialog = new ErrorDialog(this,true) ;
                dialog.setVisible(true);
            }
            
        }
    }//GEN-LAST:event_CtoAActionPerformed

    void updateStackA() {
        DefaultTableModel model = (DefaultTableModel) StackATable.getModel();

        model.setRowCount(0);

        for (int i = stackA.maxsize - 1; i >= 0; i--) {
            if (i <= stackA.top) {
                model.addRow(new Object[]{ stackA.stackThing[i] });
            } else {
                model.addRow(new Object[]{ "" });
            }
        }
    }
    void updateStackB() {
        DefaultTableModel model = (DefaultTableModel) StackBTable.getModel();

        model.setRowCount(0);

        for (int i = stackB.maxsize - 1; i >= 0; i--) {
            if (i <= stackB.top) {
                model.addRow(new Object[]{ stackB.stackThing[i] });
            } else {
                model.addRow(new Object[]{ "" });
            }
        }
    }
    void updateStackC() {
        DefaultTableModel model = (DefaultTableModel) StackCTable.getModel();

        model.setRowCount(0);

        for (int i = stackC.maxsize - 1; i >= 0; i--) {
            if (i <= stackC.top) {
                model.addRow(new Object[]{ stackC.stackThing[i] });
            } else {
                model.addRow(new Object[]{ "" });
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtoB;
    private javax.swing.JButton AtoC;
    private javax.swing.JButton BtoA;
    private javax.swing.JButton BtoC;
    private javax.swing.JButton CtoA;
    private javax.swing.JButton CtoB;
    private javax.swing.JTable StackATable;
    private javax.swing.JTable StackBTable;
    private javax.swing.JTable StackCTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
