pythonLesson = {'SUPANAT','TEERAPON','KAWINWAT','KIDSAKORN','PHON','SURACHAD'}
javaLesson = {'PAWARIS','SUPANAT','PONGSAKORN','RATTANACHAT','PHON','SURACHAD'}
cppLesson = {'SUPANAT','TEERAPON','KAWINWAT','RATTANACHAT','SURACHAD','MATCHAKAN'}

print("==================================================================")
print("Analysis of Elective Programming Course Registration")
print("==================================================================")
print("Registration Data for Each Course :")
print(f"Python ({len(pythonLesson)} students) : {pythonLesson}")
print(f"Java ({len(javaLesson)} students) : {javaLesson}")
print(f"C++ ({len(cppLesson)} students) : {cppLesson}\n")
print("==================================================================")
print("Analysis Results:")
print("==================================================================")
print("Enrolled in all 3 courses (2 students):")
print(f"Names: {pythonLesson&javaLesson&cppLesson}\n")
print("2. Enrolled in only Python (1 students):")
print(f"Names: {pythonLesson-javaLesson-cppLesson}\n")
print("3. Enrolled in only Java (2 students):")
print(f"Names: {javaLesson-pythonLesson-cppLesson}\n")
print("4.Enrolled in only C++ (1 students):")
print(f"Names: {cppLesson-javaLesson-pythonLesson}\n")
print("5. Enrolled in Python and Java only (1 students):")
print(f"Names: {pythonLesson&javaLesson-cppLesson}\n")
print("6. Enrolled in Python and C++ only (2 students):")
print(f"Names: {pythonLesson&cppLesson-javaLesson}\n")
print("7. Enrolled in Java and C++ only (1 students):")
print(f"Names: {javaLesson&cppLesson-pythonLesson}\n")
print("8. Enrolled in at least 2 courses (6 students):")
print(f"Names: {(pythonLesson&cppLesson)|(pythonLesson&javaLesson)|(cppLesson&javaLesson)}\n")