/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2103_assignment1;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author ponlawatchangto
 */
public class MainGUI extends javax.swing.JFrame {

    int maxsize;
    SportEquipment[] LA;
    int LB;
    int UB;
    int amount;
    int id;
    int index;

    TableGUI tableGUI;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();

        index = 0;
        maxsize = 10;
        LA = new SportEquipment[maxsize];
        LB = 0;
        UB = maxsize - 1;
        amount = 0;
        id = 0;
        updateInfo();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        InsertAtLastButton = new javax.swing.JButton();
        InsertByIndexButton = new javax.swing.JButton();
        DeleteByIndexButton = new javax.swing.JButton();
        SortViaIDButton = new javax.swing.JButton();
        SortViaPriceButton = new javax.swing.JButton();
        SearchViaIDButton = new javax.swing.JButton();
        ChangeMaxsizeButton = new javax.swing.JButton();
        ShowTableButton = new javax.swing.JButton();
        UpdateViaIDButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ImageFrame = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ItemIndexSign = new javax.swing.JLabel();
        LeftButton = new javax.swing.JButton();
        RigthButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MaxsizeSign = new javax.swing.JLabel();
        AmountSign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(25, 24, 59));

        jLabel1.setFont(new java.awt.Font("Anakotmai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Assignment#1 6601001123");

        jPanel2.setBackground(new java.awt.Color(112, 137, 147));
        jPanel2.setMaximumSize(new java.awt.Dimension(243, 473));
        jPanel2.setMinimumSize(new java.awt.Dimension(243, 473));

        InsertAtLastButton.setBackground(new java.awt.Color(231, 242, 239));
        InsertAtLastButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        InsertAtLastButton.setText("Insert at Last");
        InsertAtLastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertAtLastButtonActionPerformed(evt);
            }
        });

        InsertByIndexButton.setBackground(new java.awt.Color(231, 242, 239));
        InsertByIndexButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        InsertByIndexButton.setText("Insert at Certain Index");
        InsertByIndexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertByIndexButtonActionPerformed(evt);
            }
        });

        DeleteByIndexButton.setBackground(new java.awt.Color(231, 242, 239));
        DeleteByIndexButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        DeleteByIndexButton.setText("Delete by Index");
        DeleteByIndexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteByIndexButtonActionPerformed(evt);
            }
        });

        SortViaIDButton.setBackground(new java.awt.Color(231, 242, 239));
        SortViaIDButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        SortViaIDButton.setText("Sort Via ID");
        SortViaIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortViaIDButtonActionPerformed(evt);
            }
        });

        SortViaPriceButton.setBackground(new java.awt.Color(231, 242, 239));
        SortViaPriceButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        SortViaPriceButton.setText("Sort Via Price");
        SortViaPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortViaPriceButtonActionPerformed(evt);
            }
        });

        SearchViaIDButton.setBackground(new java.awt.Color(231, 242, 239));
        SearchViaIDButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        SearchViaIDButton.setText("Search Via ID");
        SearchViaIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchViaIDButtonActionPerformed(evt);
            }
        });

        ChangeMaxsizeButton.setBackground(new java.awt.Color(231, 242, 239));
        ChangeMaxsizeButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        ChangeMaxsizeButton.setText("Change Maxsize");
        ChangeMaxsizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeMaxsizeButtonActionPerformed(evt);
            }
        });

        ShowTableButton.setBackground(new java.awt.Color(231, 242, 239));
        ShowTableButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        ShowTableButton.setText("Show Table");
        ShowTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTableButtonActionPerformed(evt);
            }
        });

        UpdateViaIDButton.setBackground(new java.awt.Color(231, 242, 239));
        UpdateViaIDButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        UpdateViaIDButton.setText("Update Via ID");
        UpdateViaIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateViaIDButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateViaIDButton)
                    .addComponent(SearchViaIDButton)
                    .addComponent(SortViaPriceButton)
                    .addComponent(SortViaIDButton)
                    .addComponent(InsertAtLastButton)
                    .addComponent(InsertByIndexButton)
                    .addComponent(DeleteByIndexButton)
                    .addComponent(ChangeMaxsizeButton)
                    .addComponent(ShowTableButton))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(InsertAtLastButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsertByIndexButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteByIndexButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SortViaIDButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SortViaPriceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchViaIDButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateViaIDButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChangeMaxsizeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowTableButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(231, 242, 239));
        jPanel3.setMaximumSize(new java.awt.Dimension(477, 473));
        jPanel3.setMinimumSize(new java.awt.Dimension(477, 473));
        jPanel3.setPreferredSize(new java.awt.Dimension(477, 473));

        jPanel5.setBackground(new java.awt.Color(231, 242, 239));

        ImageFrame.setFont(new java.awt.Font("Anakotmai", 0, 12)); // NOI18N
        ImageFrame.setText("Image can't be shown");
        ImageFrame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ImageFrame.setPreferredSize(new java.awt.Dimension(150, 150));
        ImageFrame.setSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImageFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ImageFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(231, 242, 239));

        jLabel2.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        jLabel3.setText("Type :");

        jLabel4.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        jLabel4.setText("Price :");

        jPanel4.setBackground(new java.awt.Color(231, 242, 239));

        ItemIndexSign.setBackground(new java.awt.Color(0, 0, 0));
        ItemIndexSign.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        ItemIndexSign.setText("Item Index : -");

        LeftButton.setBackground(new java.awt.Color(25, 24, 59));
        LeftButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        LeftButton.setForeground(new java.awt.Color(255, 255, 255));
        LeftButton.setText("<<<");
        LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftButtonActionPerformed(evt);
            }
        });

        RigthButton.setBackground(new java.awt.Color(25, 24, 59));
        RigthButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        RigthButton.setForeground(new java.awt.Color(255, 255, 255));
        RigthButton.setText(">>>");
        RigthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RigthButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LeftButton)
                .addGap(29, 29, 29)
                .addComponent(RigthButton)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ItemIndexSign)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ItemIndexSign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LeftButton)
                    .addComponent(RigthButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        jLabel5.setText("-");

        jLabel6.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        jLabel6.setText("-");

        jLabel7.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        jLabel7.setText("-");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MaxsizeSign.setFont(new java.awt.Font("Anakotmai", 0, 14)); // NOI18N
        MaxsizeSign.setForeground(new java.awt.Color(255, 255, 255));
        MaxsizeSign.setText("Maxsize :");

        AmountSign.setFont(new java.awt.Font("Anakotmai", 0, 14)); // NOI18N
        AmountSign.setForeground(new java.awt.Color(255, 255, 255));
        AmountSign.setText("Item Amount :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaxsizeSign, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AmountSign, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(MaxsizeSign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AmountSign)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertAtLastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertAtLastButtonActionPerformed
        // TODO add your handling code here:
        InsertAtLastGUI obj = new InsertAtLastGUI(this, true);
        obj.setVisible(true);
        if (obj.confirm) {
            try {
                String name = obj.getjTextPane4();
                int type = Integer.parseInt(obj.getjTextPane5());
                float price = Float.parseFloat(obj.getjTextPane6());
                String image = obj.getjTextPane7();

                SportEquipment temp = new SportEquipment(++id, name, type, price, image);
                System.out.println("Insert At Last is operating . . .");
                InsertByIndex(LA, temp, amount, amount);
                System.out.println("Insert At Last operating is success !");
                updateInfo(temp);
                updateTableAtTableGUI();
            } catch (Exception e) {
                System.out.println(e);
                jLabel5.setText("Error");
                jLabel6.setText("-");
                jLabel7.setText("-");
            }
        }

    }//GEN-LAST:event_InsertAtLastButtonActionPerformed

    private void InsertByIndexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertByIndexButtonActionPerformed
        // TODO add your handling code here:
        InsertByIndexGUI obj = new InsertByIndexGUI(this, true);
        obj.setVisible(true);
        if (obj.confirm) {
            if (obj.getIndex() > amount || obj.getIndex() < 0) {
                ErrorDialog dialog = new ErrorDialog(this, true);
                dialog.setVisible(true);
                return;
            }
            try {
                String name = obj.getjTextPane4();
                int type = Integer.parseInt(obj.getjTextPane5());
                float price = Float.parseFloat(obj.getjTextPane6());
                String image = obj.getjTextPane7();

                SportEquipment temp = new SportEquipment(++id, name, type, price, image);
                System.out.println("Insert At index " + obj.getjTextPane1() + " is operating . . .");
                InsertByIndex(LA, temp, Integer.parseInt(obj.getjTextPane1()), amount);
                System.out.println("Insert At Certain index operating is success !");
                updateInfo(temp);
                updateTableAtTableGUI();
            } catch (Exception e) {
                System.out.println(e);
                jLabel5.setText("Error");
                jLabel6.setText("-");
                jLabel7.setText("-");
            }
        }
    }//GEN-LAST:event_InsertByIndexButtonActionPerformed

    private void DeleteByIndexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteByIndexButtonActionPerformed
        // TODO add your handling code here:
        DeleteByIndex dialog = new DeleteByIndex(this, true);
        dialog.setVisible(true);
        if (dialog.confirm) {
            System.out.println("Delete At Last is operating . . .");
            DeleteByIndex(LA, dialog.index, amount);
            System.out.println("Delete At Last operating is success !");
            index = amount - 1;
            updateInfo();
            updateTableAtTableGUI();
        }
    }//GEN-LAST:event_DeleteByIndexButtonActionPerformed

    private void SortViaIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortViaIDButtonActionPerformed
        // TODO add your handling code here:
        SortById();

        updateInfo();

        updateTableAtTableGUI();
    }//GEN-LAST:event_SortViaIDButtonActionPerformed

    private void SortViaPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortViaPriceButtonActionPerformed
        // TODO add your handling code here:
        SortByPrice();

        updateInfo();

        updateTableAtTableGUI();
    }//GEN-LAST:event_SortViaPriceButtonActionPerformed

    private void SearchViaIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchViaIDButtonActionPerformed
        // TODO add your handling code here:
        InputIDGUI dialog_inputID = new InputIDGUI(this, true);
        dialog_inputID.setVisible(true);
        if (!dialog_inputID.getConfirm()) {
            return;
        }
        index = dialog_inputID.getID();
        updateInfo();
    }//GEN-LAST:event_SearchViaIDButtonActionPerformed

    private void LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftButtonActionPerformed
        // TODO add your handling code here:
        if (index > 0) {
            index--;
        }
        updateInfo();
    }//GEN-LAST:event_LeftButtonActionPerformed

    private void RigthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RigthButtonActionPerformed
        // TODO add your handling code here:
        if (index < amount - 1) {
            index++;
        }
        updateInfo();
    }//GEN-LAST:event_RigthButtonActionPerformed

    private void ChangeMaxsizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeMaxsizeButtonActionPerformed
        // TODO add your handling code here:
        InputNewSize dialog = new InputNewSize(this, true);
        dialog.setVisible(true);

        if (dialog.getConfirm()) {
            try {
                int newSize = dialog.getNewSize();
                if (newSize < this.amount) {
                    newSize = this.amount;
                }

                SportEquipment[] newLA = new SportEquipment[newSize];

                System.out.println("Transferring data to new array...");
                for (int i = 0; i < this.amount; i++) {
                    newLA[i] = this.LA[i];
                }

                this.LA = newLA;
                this.maxsize = newSize;
                this.UB = newSize - 1;

                System.out.println("Max size changed successfully to " + this.maxsize);

                updateInfo();
                updateTableAtTableGUI();

            } catch (NumberFormatException e) {
                ErrorDialog error = new ErrorDialog(this, true);
                error.setVisible(true);
            }
        }
    }//GEN-LAST:event_ChangeMaxsizeButtonActionPerformed

    private void ShowTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTableButtonActionPerformed
        // TODO add your handling code here:
        if (tableGUI == null) {
            tableGUI = new TableGUI(this, false);
        }
        tableGUI.setVisible(true);
    }//GEN-LAST:event_ShowTableButtonActionPerformed

    private void UpdateViaIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateViaIDButtonActionPerformed
        // TODO add your handling code here:
        InputIDGUI inputIDGUI = new InputIDGUI(this,true) ;
        inputIDGUI.setVisible(true) ;
        if (!inputIDGUI.getConfirm()) return ;
        
        UpdateItemGUI updateDialog = new UpdateItemGUI(this,true,inputIDGUI.getID()) ;
        updateDialog.setVisible(true);
        if(!updateDialog.getConfirm()) return ;
        
        SportEquipment item = LA[updateDialog.id] ;
        item.setName(updateDialog.getjTextPane4());
        item.setType(updateDialog.getjTextPane5()); 
        item.setPrice(updateDialog.getjTextPane6()); 
        item.setImage(updateDialog.getjTextPane7()); 
        updateInfo(item) ;
        updateTableAtTableGUI();
    }//GEN-LAST:event_UpdateViaIDButtonActionPerformed

    void InsertByIndex(SportEquipment[] LA, SportEquipment Item, int K, int N) {
        if (N >= maxsize) {
            return;
        }
        if (K < 0 || K > N) {
            return;
        }
        int J = N;
        while (J >= K) {
            LA[J + 1] = LA[J];
            J--;
        }
        LA[K] = Item;
        this.amount = N + 1;
    }

    void DeleteByIndex(SportEquipment[] LA, int K, int N) {
        if(N<0) return ;
        for (int J = K; J < N - 1; J++) {
            LA[J] = LA[J + 1];
        }
        this.amount = N - 1;
    }

    int Search(SportEquipment[] LA, int N, SportEquipment Item) {
        LA[N] = Item;
        int LOC = 0;
        while (LA[LOC] != Item) {
            LOC++;
        }
        if (LOC == N) {
            LOC = -1;
        }
        return LOC;
    }

    void SortById() {
        if (amount < 2) {
            return;
        }
        for (int i = 0; i < amount - 1; i++) {
            for (int j = 0; j < amount - i - 1; j++) {
                if (LA[j].getID() > LA[j + 1].getID()) {
                    SportEquipment temp = LA[j];
                    LA[j] = LA[j + 1];
                    LA[j + 1] = temp;
                }
            }
        }
        System.out.println("Array sorted by ID.");
    }

    void SortByPrice() {
        if (amount < 2) {
            return;
        }
        for (int i = 0; i < amount - 1; i++) {
            for (int j = 0; j < amount - i - 1; j++) {
                if (LA[j].getPrice() > LA[j + 1].getPrice()) {
                    SportEquipment temp = LA[j];
                    LA[j] = LA[j + 1];
                    LA[j + 1] = temp;
                }
            }
        }
        System.out.println("Array sorted by Price.");
    }

    void updateInfo() {
        if (index < amount) {
            ItemIndexSign.setText("Item Index : " + index);
            jLabel5.setText(LA[index].getName());
            jLabel6.setText(LA[index].getType() + "");
            jLabel7.setText(LA[index].getPrice() + "");

            displayImage(LA[index].getImage());
        }
        MaxsizeSign.setText("Maxsize : " + maxsize);
        AmountSign.setText("Item Amount : " + amount);
    }

    void updateInfo(SportEquipment itemToShow) {
        if (itemToShow != null) {
            int index = Search(LA, amount, itemToShow);
            this.index = index;
            ItemIndexSign.setText("Item Index : " + index);
            jLabel5.setText(itemToShow.getName());
            jLabel6.setText(String.valueOf(itemToShow.getType()));
            jLabel7.setText(itemToShow.getPrice() + "");

            displayImage(itemToShow.getImage());
        } else {
            jLabel5.setText("Error: Item not found");
            jLabel6.setText("-");
            jLabel7.setText("-");
        }
        MaxsizeSign.setText("Maxsize : " + maxsize);
        AmountSign.setText("Item Amount : " + amount);
    }

    void displayImage(String imageName) {
        try {
            ImageIcon image = new ImageIcon(getClass().getResource("/image/" + imageName + ".jpg"));
            Image temp_image = image.getImage();

            int FrameWidth = 150;
            int FrameHeight = 150;
            int pictureWidth = image.getIconWidth();
            int pictureHeight = image.getIconHeight();

            double widthRatio = (double) FrameWidth / pictureWidth;
            double heightRatio = (double) FrameHeight / pictureHeight;

            double ratio = Math.min(widthRatio, heightRatio);

            int newWidth = (int) (pictureWidth * ratio);
            int newHeight = (int) (pictureHeight * ratio);

            temp_image = temp_image.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);

            image = new ImageIcon(temp_image);
            ImageFrame.setIcon(image);
            ImageFrame.setText("");

        } catch (Exception e) {
            ImageFrame.setIcon(null);
            ImageFrame.setText("Image not found");
            System.out.println("Error loading image: " + imageName);
        }
    }

    void updateTableAtTableGUI() {
        if (tableGUI != null && tableGUI.isVisible()) {
            tableGUI.updateTable();
        }
    }

    int getAmount() {
        return amount;
    }

    SportEquipment[] getLA() {
        return LA;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountSign;
    private javax.swing.JButton ChangeMaxsizeButton;
    private javax.swing.JButton DeleteByIndexButton;
    private javax.swing.JLabel ImageFrame;
    private javax.swing.JButton InsertAtLastButton;
    private javax.swing.JButton InsertByIndexButton;
    private javax.swing.JLabel ItemIndexSign;
    private javax.swing.JButton LeftButton;
    private javax.swing.JLabel MaxsizeSign;
    private javax.swing.JButton RigthButton;
    private javax.swing.JButton SearchViaIDButton;
    private javax.swing.JButton ShowTableButton;
    private javax.swing.JButton SortViaIDButton;
    private javax.swing.JButton SortViaPriceButton;
    private javax.swing.JButton UpdateViaIDButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
