/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2103_assignment1;

import java.awt.Image;
import java.util.HashSet;
import javax.swing.ImageIcon;

/**
 *
 * @author ponlawatchangto
 */
public class MainGUI extends javax.swing.JFrame {

    int maxsize;
    DNode Start;
    DNode Last;
    int amount;
    int id;
    DNode currentNode;

    TableGUI tableGUI;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();

        maxsize = 10;
        Start = null;
        Last = null;
        amount = 0;
        id = 0;
        updateInfo();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        InsertAtLastButton = new javax.swing.JButton();
        InsertBehindItemID = new javax.swing.JButton();
        DeleteByIDButton = new javax.swing.JButton();
        SearchViaIDButton = new javax.swing.JButton();
        ChangeMaxsizeButton = new javax.swing.JButton();
        ShowTableButton = new javax.swing.JButton();
        UpdateViaIDButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ImageFrame = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        LeftButton = new javax.swing.JButton();
        RigthButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MaxsizeSign = new javax.swing.JLabel();
        AmountSign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Anakotmai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Assignment#4.1 6601001123");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(243, 473));
        jPanel2.setMinimumSize(new java.awt.Dimension(243, 473));

        InsertAtLastButton.setBackground(new java.awt.Color(255, 153, 0));
        InsertAtLastButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        InsertAtLastButton.setForeground(new java.awt.Color(0, 0, 0));
        InsertAtLastButton.setText("Insert at Last");
        InsertAtLastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertAtLastButtonActionPerformed(evt);
            }
        });

        InsertBehindItemID.setBackground(new java.awt.Color(255, 153, 0));
        InsertBehindItemID.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        InsertBehindItemID.setForeground(new java.awt.Color(0, 0, 0));
        InsertBehindItemID.setText("Insert behind item ID");
        InsertBehindItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBehindItemIDActionPerformed(evt);
            }
        });

        DeleteByIDButton.setBackground(new java.awt.Color(255, 153, 0));
        DeleteByIDButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        DeleteByIDButton.setForeground(new java.awt.Color(0, 0, 0));
        DeleteByIDButton.setText("Delete by ID");
        DeleteByIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteByIDButtonActionPerformed(evt);
            }
        });

        SearchViaIDButton.setBackground(new java.awt.Color(255, 153, 0));
        SearchViaIDButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        SearchViaIDButton.setForeground(new java.awt.Color(0, 0, 0));
        SearchViaIDButton.setText("Search Via ID");
        SearchViaIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchViaIDButtonActionPerformed(evt);
            }
        });

        ChangeMaxsizeButton.setBackground(new java.awt.Color(255, 153, 0));
        ChangeMaxsizeButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        ChangeMaxsizeButton.setForeground(new java.awt.Color(0, 0, 0));
        ChangeMaxsizeButton.setText("Change Maxsize");
        ChangeMaxsizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeMaxsizeButtonActionPerformed(evt);
            }
        });

        ShowTableButton.setBackground(new java.awt.Color(255, 153, 0));
        ShowTableButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        ShowTableButton.setForeground(new java.awt.Color(0, 0, 0));
        ShowTableButton.setText("Show Table");
        ShowTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTableButtonActionPerformed(evt);
            }
        });

        UpdateViaIDButton.setBackground(new java.awt.Color(255, 153, 0));
        UpdateViaIDButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        UpdateViaIDButton.setForeground(new java.awt.Color(0, 0, 0));
        UpdateViaIDButton.setText("Update Via ID");
        UpdateViaIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateViaIDButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateViaIDButton)
                    .addComponent(SearchViaIDButton)
                    .addComponent(InsertAtLastButton)
                    .addComponent(InsertBehindItemID)
                    .addComponent(DeleteByIDButton)
                    .addComponent(ChangeMaxsizeButton)
                    .addComponent(ShowTableButton))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(InsertAtLastButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsertBehindItemID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteByIDButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchViaIDButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateViaIDButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChangeMaxsizeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowTableButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setMaximumSize(new java.awt.Dimension(477, 473));
        jPanel3.setMinimumSize(new java.awt.Dimension(477, 473));
        jPanel3.setPreferredSize(new java.awt.Dimension(477, 473));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        ImageFrame.setFont(new java.awt.Font("Anakotmai", 0, 12)); // NOI18N
        ImageFrame.setForeground(new java.awt.Color(255, 255, 255));
        ImageFrame.setText("Image can't be shown");
        ImageFrame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ImageFrame.setPreferredSize(new java.awt.Dimension(150, 150));
        ImageFrame.setSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImageFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ImageFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Type :");

        jLabel4.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price :");

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        LeftButton.setBackground(new java.awt.Color(255, 153, 0));
        LeftButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        LeftButton.setForeground(new java.awt.Color(0, 0, 0));
        LeftButton.setText("<<<");
        LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftButtonActionPerformed(evt);
            }
        });

        RigthButton.setBackground(new java.awt.Color(255, 153, 0));
        RigthButton.setFont(new java.awt.Font("Anakotmai", 1, 14)); // NOI18N
        RigthButton.setForeground(new java.awt.Color(0, 0, 0));
        RigthButton.setText(">>>");
        RigthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RigthButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LeftButton)
                .addGap(29, 29, 29)
                .addComponent(RigthButton)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LeftButton)
                    .addComponent(RigthButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("-");

        jLabel6.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-");

        jLabel7.setFont(new java.awt.Font("Anakotmai", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("-");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MaxsizeSign.setFont(new java.awt.Font("Anakotmai", 0, 14)); // NOI18N
        MaxsizeSign.setForeground(new java.awt.Color(255, 255, 255));
        MaxsizeSign.setText("Maxsize :");

        AmountSign.setFont(new java.awt.Font("Anakotmai", 0, 14)); // NOI18N
        AmountSign.setForeground(new java.awt.Color(255, 255, 255));
        AmountSign.setText("Item Amount :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaxsizeSign, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AmountSign, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(MaxsizeSign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AmountSign)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertAtLastButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_InsertAtLastButtonActionPerformed
        // TODO add your handling code here:
        InsertAtLastGUI obj = new InsertAtLastGUI(this, true);
        obj.setVisible(true);
        if (obj.confirm) {
            try {
                String name = obj.getjTextPane4();
                int type = Integer.parseInt(obj.getjTextPane5());
                float price = Float.parseFloat(obj.getjTextPane6());
                String image = obj.getjTextPane7();

                SportEquipment temp = new SportEquipment(++id, name, type, price, image);
                DNode node = new DNode();
                node.Infor = temp;
                System.out.println("Insert At Last is operating . . .");
                InsertAtLast(node);
                System.out.println("Insert At Last operating is success !");
                amount++;
                updateInfo(node);
                updateTableAtTableGUI();
            } catch (Exception e) {
                System.out.println(e);
                jLabel5.setText("Error");
                jLabel6.setText("-");
                jLabel7.setText("-");
            }
        }

    }// GEN-LAST:event_InsertAtLastButtonActionPerformed

    private void InsertBehindItemIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_InsertBehindItemIDActionPerformed
        // TODO add your handling code here:
        InsertBehindItemIDGUI obj = new InsertBehindItemIDGUI(this, true);
        obj.setVisible(true);
        if (obj.confirm) {
            DNode Ptr = Search(obj.getItemID());
            if (Ptr == null) {
                ErrorDialog dialog = new ErrorDialog(this, true);
                dialog.setVisible(true);
                return;
            }
            try {
                String name = obj.getjTextPane4();
                int type = Integer.parseInt(obj.getjTextPane5());
                float price = Float.parseFloat(obj.getjTextPane6());
                String image = obj.getjTextPane7();

                SportEquipment temp = new SportEquipment(++id, name, type, price, image);
                DNode node = new DNode();
                node.Infor = temp;
                System.out.println("Insert At index " + obj.getjTextPane1() + " is operating . . .");
                
                if (Ptr.Forw == null) {
                    InsertAtLast(node);
                } else {
                    InsertByLoc(Ptr, Ptr.Forw, node);
                }
                
                System.out.println("Insert At Certain index operating is success !");
                amount++;
                updateInfo(node);
                updateTableAtTableGUI();
            } catch (Exception e) {
                System.out.println(e);
                jLabel5.setText("Error");
                jLabel6.setText("-");
                jLabel7.setText("-");
            }
        }
    }// GEN-LAST:event_InsertBehindItemIDActionPerformed

    private void DeleteByIDButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DeleteByIDButtonActionPerformed
        // TODO add your handling code here:
        DeleteByID dialog = new DeleteByID(this, true);
        dialog.setVisible(true);
        try {
            if (dialog.confirm) {
                System.out.println("Delete At Last is operating . . .");
                // DeleteByIndex(LA, dialog.index, amount);

                DNode item = Search(dialog.id);
                if (item == null) { // Add null check
                    ErrorDialog error = new ErrorDialog(this, true);
                    error.setVisible(true);
                    return;
                }
                if (Start == item) {
                    DeleteAtFirst();
                } else if (Last == item) {
                    DeleteAtLast();
                } else {
                    DeleteByLoc(item);
                }

                System.out.println("Delete At Last operating is success !");
                // index = amount - 1;
                amount--;
                updateInfo(Start);
                updateTableAtTableGUI();
            }
        } catch (Exception e) {
            ErrorDialog error = new ErrorDialog(this, true);
            error.setVisible(true);
            return;
        }
    }// GEN-LAST:event_DeleteByIDButtonActionPerformed

    private void SearchViaIDButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SearchViaIDButtonActionPerformed
        InputIDGUI dialog_inputID = new InputIDGUI(this, true);
        dialog_inputID.setVisible(true);
        if (!dialog_inputID.getConfirm()) {
            return;
        }
        currentNode = Search(dialog_inputID.getID());
        updateInfo();
    }// GEN-LAST:event_SearchViaIDButtonActionPerformed

    private void LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LeftButtonActionPerformed
        if (currentNode.Back != null) {
            currentNode = currentNode.Back;
        }
        updateInfo();
    }// GEN-LAST:event_LeftButtonActionPerformed

    private void RigthButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RigthButtonActionPerformed
        // if (index < amount - 1) {
        // index++;
        // }
        if (currentNode.Forw != null) {
            currentNode = currentNode.Forw;
        }
        updateInfo();
    }// GEN-LAST:event_RigthButtonActionPerformed

    private void ChangeMaxsizeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ChangeMaxsizeButtonActionPerformed
        // TODO add your handling code here:
        InputNewSize dialog = new InputNewSize(this, true);
        dialog.setVisible(true);

        if (dialog.getConfirm()) {
            try {
                int newSize = dialog.getNewSize();
                if (newSize < this.amount) {
                    newSize = this.amount;
                }

                this.maxsize = newSize;

                System.out.println("Max size changed successfully to " + this.maxsize);

                updateInfo();
                updateTableAtTableGUI();

            } catch (Exception e) {
                ErrorDialog error = new ErrorDialog(this, true);
                error.setVisible(true);
            }
        }
    }// GEN-LAST:event_ChangeMaxsizeButtonActionPerformed

    private void ShowTableButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ShowTableButtonActionPerformed
        if (tableGUI == null) {
            tableGUI = new TableGUI(this, false);
        }
        tableGUI.setVisible(true);
    }// GEN-LAST:event_ShowTableButtonActionPerformed

    private void UpdateViaIDButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UpdateViaIDButtonActionPerformed
        // TODO add your handling code here:
        InputIDGUI inputIDGUI = new InputIDGUI(this, true);
        inputIDGUI.setVisible(true);
        if (!inputIDGUI.getConfirm()) {
            return;
        }

        UpdateItemGUI updateDialog = new UpdateItemGUI(this, true, inputIDGUI.getID());
        updateDialog.setVisible(true);
        if (!updateDialog.getConfirm()) {
            return;
        }

        DNode item = Search(updateDialog.id);
        item.Infor.setName(updateDialog.getjTextPane4());
        item.Infor.setType(updateDialog.getjTextPane5());
        item.Infor.setPrice(updateDialog.getjTextPane6());
        item.Infor.setImage(updateDialog.getjTextPane7());

        updateInfo(item);
        updateTableAtTableGUI();
    }// GEN-LAST:event_UpdateViaIDButtonActionPerformed

    void InsertByLoc(DNode LocA, DNode LocB, DNode New) {
        System.out.println("Entering InsertByLoc");
        LocA.Forw = New;
        New.Forw = LocB;
        LocB.Back = New;
        New.Back = LocA;
        System.out.println("Exting InsertByLoc");
        return;
    }

    void InsertAtLast(DNode New) {
        System.out.println("Entering InsertAtLast");
        if (Last != null) {
            DNode LastNode = Last;
            LastNode.Forw = New;
            New.Back = LastNode;
            Last = New;
        } else {
            Start = Last = New;
        }
        System.out.println("Exting InsertAtLast");
        return;
    }

    void InsertAtFirst(DNode New) {
        System.out.println("Entering InsertAtFirst");
        if (Start != null) {
            DNode FirstNode = Start;
            New.Forw = FirstNode;
            FirstNode.Back = New;
            Start = New;
        } else {
            Start = Last = New;
        }
        System.out.println("Exiting InsertAtLast");
    }

    void DeleteByLoc(DNode Loc) {
        System.out.println("Entering DeleteByLoc");
        if (Loc == null || Loc.Back == null || Loc.Forw == null) {
            return; // Safety check
        }
        Loc.Back.Forw = Loc.Forw;
        Loc.Forw.Back = Loc.Back;
        System.out.println("Exiting DeleteByLoc");
        return;
    }

    void DeleteAtFirst() {
        System.out.println("Entering DeleteAtFirst");
        if (Start.Forw != null) {
            Start = Start.Forw;
            Start.Back = null; // Set new Start's Back to null
        } else {
            Start = Last = null;
        }
        System.out.println("Exiting DeleteAtFirst");
    }

    void DeleteAtLast() {
        System.out.println("Entering DeleteAtLast");
        if (Last.Back != null) {
            Last = Last.Back;
            Last.Forw = null; // Set new Last's Forw to null
        } else {
            Start = Last = null;
        }
        System.out.println("Exiting DeleteAtLast");
    }

    DNode Search(int id) {
        System.out.println("Entering Search Method");
        DNode Loc = null;
        DNode Ptr = Start;
        while (Ptr != null) {
            if (id == Ptr.Infor.getID()) {
                System.out.println("Search : Found ! Loc = Ptr");
                Loc = Ptr;
                break;
            }
            System.out.println("Search : Not Found yet. Ptr = Ptr.Forw ");
            Ptr = Ptr.Forw;
        }
        if (Loc != null) {
            System.out.println("Search : Found !");
        } else {
            System.out.println("Search : Not Found !");
        }
        System.out.println("Exiting Search Method");
        return Loc;
    }

    // void SortById() {
    // if (amount < 2) {
    // return;
    // }
    // for (int i = 0; i < amount - 1; i++) {
    // for (int j = 0; j < amount - i - 1; j++) {
    // if (LA[j].getID() > LA[j + 1].getID()) {
    // SportEquipment temp = LA[j];
    // LA[j] = LA[j + 1];
    // LA[j + 1] = temp;
    // }
    // }
    // }
    // System.out.println("Array sorted by ID.");
    // }
    //
    // void SortByPrice() {
    // if (amount < 2) {
    // return;
    // }
    // for (int i = 0; i < amount - 1; i++) {
    // for (int j = 0; j < amount - i - 1; j++) {
    // if (LA[j].getPrice() > LA[j + 1].getPrice()) {
    // SportEquipment temp = LA[j];
    // LA[j] = LA[j + 1];
    // LA[j + 1] = temp;
    // }
    // }
    // }
    // System.out.println("Array sorted by Price.");
    // }
    
    void updateInfo() {
        if (currentNode != null) {
            jLabel5.setText(currentNode.Infor.getName());
            jLabel6.setText(currentNode.Infor.getType() + "");
            jLabel7.setText(currentNode.Infor.getPrice() + "");

            displayImage(currentNode.Infor.getImage());
        }
        MaxsizeSign.setText("Maxsize : " + maxsize);
        AmountSign.setText("Item Amount : " + amount);
    }

    void updateInfo(DNode itemToShow) {
        if (itemToShow != null) {
            currentNode = itemToShow;
            jLabel5.setText(currentNode.Infor.getName());
            jLabel6.setText(currentNode.Infor.getType() + "");
            jLabel7.setText(currentNode.Infor.getPrice() + "");

            displayImage(currentNode.Infor.getImage());
        } else {
            jLabel5.setText("-");
            jLabel6.setText("-");
            jLabel7.setText("-");
            ImageFrame.setIcon(null);
            ImageFrame.setText("Image can't be shown");
        }
        MaxsizeSign.setText("Maxsize : " + maxsize);
        AmountSign.setText("Item Amount : " + amount);
    }

    void displayImage(String imageName) {
        try {
            ImageIcon image = new ImageIcon(getClass().getResource("/image/" + imageName + ".jpg"));
            Image temp_image = image.getImage();

            int FrameWidth = 150;
            int FrameHeight = 150;
            int pictureWidth = image.getIconWidth();
            int pictureHeight = image.getIconHeight();

            double widthRatio = (double) FrameWidth / pictureWidth;
            double heightRatio = (double) FrameHeight / pictureHeight;

            double ratio = Math.min(widthRatio, heightRatio);

            int newWidth = (int) (pictureWidth * ratio);
            int newHeight = (int) (pictureHeight * ratio);

            temp_image = temp_image.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);

            image = new ImageIcon(temp_image);
            ImageFrame.setIcon(image);
            ImageFrame.setText("");

        } catch (Exception e) {
            ImageFrame.setIcon(null);
            ImageFrame.setText("Image not found");
            System.out.println("Error loading image: " + imageName);
        }
    }

    void updateTableAtTableGUI() {
        if (tableGUI != null && tableGUI.isVisible()) {
            tableGUI.updateTable();
        }
    }

    int getAmount() {
        return amount;
    }

    DNode getLinkedList() {
        return Start;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountSign;
    private javax.swing.JButton ChangeMaxsizeButton;
    private javax.swing.JButton DeleteByIDButton;
    private javax.swing.JLabel ImageFrame;
    private javax.swing.JButton InsertAtLastButton;
    private javax.swing.JButton InsertBehindItemID;
    private javax.swing.JButton LeftButton;
    private javax.swing.JLabel MaxsizeSign;
    private javax.swing.JButton RigthButton;
    private javax.swing.JButton SearchViaIDButton;
    private javax.swing.JButton ShowTableButton;
    private javax.swing.JButton UpdateViaIDButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
